# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 460)
        MainWindow.setMinimumSize(QtCore.QSize(760, 460))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 761, 441))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(60, 60))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_received_msg = QtWidgets.QWidget()
        self.tab_received_msg.setObjectName("tab_received_msg")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_received_msg)
        self.scrollArea_2.setGeometry(QtCore.QRect(463, 0, 231, 441))
        self.scrollArea_2.setStyleSheet("background-color:rgb(177, 200, 177);\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 229, 439))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(80, 390, 71, 31))
        self.label_5.setObjectName("label_5")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 120, 231, 61))
        self.widget_4.setStyleSheet("background-color: white;\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.label_17 = QtWidgets.QLabel(self.widget_4)
        self.label_17.setGeometry(QtCore.QRect(60, 10, 121, 41))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 231, 61))
        self.widget_5.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.widget_5.setObjectName("widget_5")
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        self.label_18.setGeometry(QtCore.QRect(60, 10, 121, 41))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_6.setGeometry(QtCore.QRect(0, 60, 231, 61))
        self.widget_6.setStyleSheet("background-color: white;\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_19 = QtWidgets.QLabel(self.widget_6)
        self.label_19.setGeometry(QtCore.QRect(60, 10, 121, 41))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_1 = QtWidgets.QScrollArea(self.tab_received_msg)
        self.scrollArea_1.setGeometry(QtCore.QRect(-7, 0, 471, 441))
        self.scrollArea_1.setStyleSheet("background-color:rgb(138, 178, 144);")
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 469, 439))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setGeometry(QtCore.QRect(80, 170, 281, 41))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setGeometry(QtCore.QRect(220, 130, 71, 41))
        self.label_9.setObjectName("label_9")
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/IN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_received_msg, icon, "")
        self.tab_sent_msg = QtWidgets.QWidget()
        self.tab_sent_msg.setObjectName("tab_sent_msg")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_sent_msg)
        self.scrollArea_4.setGeometry(QtCore.QRect(463, 0, 231, 441))
        self.scrollArea_4.setStyleSheet("background-color:rgb(177, 200, 177);\n"
"")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(80, 400, 71, 21))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 231, 61))
        self.widget.setStyleSheet("background-color:rgb(225, 225, 225)")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 10, 121, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setGeometry(QtCore.QRect(0, 60, 231, 61))
        self.widget_2.setStyleSheet("background-color: white;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(60, 10, 121, 41))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setGeometry(QtCore.QRect(0, 120, 231, 61))
        self.widget_3.setStyleSheet("background-color: white;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setGeometry(QtCore.QRect(60, 10, 121, 41))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_sent_msg)
        self.scrollArea_3.setGeometry(QtCore.QRect(-7, 0, 471, 441))
        self.scrollArea_3.setStyleSheet("background-color:rgb(138, 178, 144);")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 469, 439))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_7.setGeometry(QtCore.QRect(120, 170, 231, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_8.setGeometry(QtCore.QRect(210, 130, 71, 41))
        self.label_8.setObjectName("label_8")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/OUT1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_sent_msg, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/Untitled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/Support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon3, "")
        self.tab_basic_info = QtWidgets.QWidget()
        self.tab_basic_info.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tab_basic_info.setObjectName("tab_basic_info")
        self.line = QtWidgets.QFrame(self.tab_basic_info)
        self.line.setGeometry(QtCore.QRect(491, 208, 181, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lable_profile_image = QtWidgets.QLabel(self.tab_basic_info)
        self.lable_profile_image.setGeometry(QtCore.QRect(539, 6, 91, 91))
        self.lable_profile_image.setStyleSheet("border-radius:45px;\n"
"background-color:rgb(89, 164, 255);")
        self.lable_profile_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lable_profile_image.setObjectName("lable_profile_image")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_basic_info)
        self.stackedWidget.setGeometry(QtCore.QRect(-2, 4, 471, 431))
        self.stackedWidget.setStyleSheet("background-color:white;\n"
"")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.inq_ans_groupBox = QtWidgets.QGroupBox(self.page_setting)
        self.inq_ans_groupBox.setGeometry(QtCore.QRect(330, 17, 121, 91))
        self.inq_ans_groupBox.setStyleSheet("border-radius:5px;\n"
"background-color:rgb(236, 232, 228);\n"
"font: 9pt \"IRANSans\";")
        self.inq_ans_groupBox.setObjectName("inq_ans_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inq_ans_groupBox)
        self.verticalLayout_2.setContentsMargins(0, 25, 25, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.inq_ans_groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.inq_ans_groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.groupBox_select_software = QtWidgets.QGroupBox(self.page_setting)
        self.groupBox_select_software.setGeometry(QtCore.QRect(15, 17, 301, 91))
        self.groupBox_select_software.setMinimumSize(QtCore.QSize(301, 91))
        self.groupBox_select_software.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_select_software.setStyleSheet("border-radius:5px;\n"
"background-color:rgb(236, 232, 228);\n"
"font: 9pt \"IRANSans\";")
        self.groupBox_select_software.setObjectName("groupBox_select_software")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_select_software)
        self.horizontalLayout.setContentsMargins(10, 25, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_select_software)
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_softwares = QtWidgets.QComboBox(self.groupBox_select_software)
        self.comboBox_softwares.setMinimumSize(QtCore.QSize(185, 0))
        self.comboBox_softwares.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_softwares.setStyleSheet("background-color:white;\n"
"font: 10pt \"IRANSans\";\n"
"border-radius: 5px;\n"
"")
        self.comboBox_softwares.setDuplicatesEnabled(False)
        self.comboBox_softwares.setObjectName("comboBox_softwares")
        self.horizontalLayout.addWidget(self.comboBox_softwares)
        self.groupBox_select_software.raise_()
        self.inq_ans_groupBox.raise_()
        self.stackedWidget.addWidget(self.page_setting)
        self.page_wallet = QtWidgets.QWidget()
        self.page_wallet.setObjectName("page_wallet")
        self.btn_cancel_login = QtWidgets.QPushButton(self.page_wallet)
        self.btn_cancel_login.setEnabled(True)
        self.btn_cancel_login.setGeometry(QtCore.QRect(45, 360, 81, 41))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_cancel_login.setFont(font)
        self.btn_cancel_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel_login.setMouseTracking(True)
        self.btn_cancel_login.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_cancel_login.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_cancel_login.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(178, 55, 77);")
        self.btn_cancel_login.setFlat(False)
        self.btn_cancel_login.setObjectName("btn_cancel_login")
        self.groupBox_temp_password = QtWidgets.QGroupBox(self.page_wallet)
        self.groupBox_temp_password.setGeometry(QtCore.QRect(60, 190, 371, 121))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(9)
        self.groupBox_temp_password.setFont(font)
        self.groupBox_temp_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_temp_password.setStyleSheet("border: 1px solid rgb(58, 178, 151);")
        self.groupBox_temp_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.groupBox_temp_password.setObjectName("groupBox_temp_password")
        self.lineEdit_mobile_number = QtWidgets.QLineEdit(self.groupBox_temp_password)
        self.lineEdit_mobile_number.setGeometry(QtCore.QRect(24, 27, 191, 35))
        self.lineEdit_mobile_number.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("B Homa")
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_mobile_number.setFont(font)
        self.lineEdit_mobile_number.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"")
        self.lineEdit_mobile_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mobile_number.setObjectName("lineEdit_mobile_number")
        self.lineEdit_temp_password = QtWidgets.QLineEdit(self.groupBox_temp_password)
        self.lineEdit_temp_password.setGeometry(QtCore.QRect(24, 73, 191, 35))
        self.lineEdit_temp_password.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("B Homa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_temp_password.setFont(font)
        self.lineEdit_temp_password.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";\n"
"")
        self.lineEdit_temp_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temp_password.setObjectName("lineEdit_temp_password")
        self.btn_request_temp_pass = QtWidgets.QPushButton(self.groupBox_temp_password)
        self.btn_request_temp_pass.setEnabled(True)
        self.btn_request_temp_pass.setGeometry(QtCore.QRect(230, 80, 131, 20))
        font = QtGui.QFont()
        font.setFamily("B Yekan")
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_request_temp_pass.setFont(font)
        self.btn_request_temp_pass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_request_temp_pass.setMouseTracking(True)
        self.btn_request_temp_pass.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_request_temp_pass.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_request_temp_pass.setStyleSheet("border:0px;\n"
"color:blue;")
        self.btn_request_temp_pass.setFlat(False)
        self.btn_request_temp_pass.setObjectName("btn_request_temp_pass")
        self.label_10 = QtWidgets.QLabel(self.groupBox_temp_password)
        self.label_10.setGeometry(QtCore.QRect(230, 34, 101, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setLineWidth(0)
        self.label_10.setObjectName("label_10")
        self.btn_enter_acnt = QtWidgets.QPushButton(self.page_wallet)
        self.btn_enter_acnt.setEnabled(True)
        self.btn_enter_acnt.setGeometry(QtCore.QRect(145, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_enter_acnt.setFont(font)
        self.btn_enter_acnt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_enter_acnt.setMouseTracking(True)
        self.btn_enter_acnt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_enter_acnt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_enter_acnt.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(58, 178, 151);")
        self.btn_enter_acnt.setFlat(False)
        self.btn_enter_acnt.setObjectName("btn_enter_acnt")
        self.btn_sign_up = QtWidgets.QPushButton(self.page_wallet)
        self.btn_sign_up.setEnabled(True)
        self.btn_sign_up.setGeometry(QtCore.QRect(320, 370, 71, 20))
        font = QtGui.QFont()
        font.setFamily("B Yekan")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_sign_up.setFont(font)
        self.btn_sign_up.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sign_up.setMouseTracking(True)
        self.btn_sign_up.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_sign_up.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_sign_up.setStyleSheet("border:0px;\n"
"color:blue;")
        self.btn_sign_up.setFlat(False)
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.btn_enter_acnt_2 = QtWidgets.QPushButton(self.page_wallet)
        self.btn_enter_acnt_2.setEnabled(True)
        self.btn_enter_acnt_2.setGeometry(QtCore.QRect(290, 20, 151, 141))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_enter_acnt_2.setFont(font)
        self.btn_enter_acnt_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_enter_acnt_2.setMouseTracking(True)
        self.btn_enter_acnt_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_enter_acnt_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_enter_acnt_2.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(58, 178, 151);\n"
"font: 11pt \"IRANSans\";\n"
"")
        self.btn_enter_acnt_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/Sale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_enter_acnt_2.setIcon(icon4)
        self.btn_enter_acnt_2.setIconSize(QtCore.QSize(128, 128))
        self.btn_enter_acnt_2.setFlat(False)
        self.btn_enter_acnt_2.setObjectName("btn_enter_acnt_2")
        self.label_3 = QtWidgets.QLabel(self.page_wallet)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 131, 111))
        self.label_3.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(58, 178, 151);\n"
"font: 11pt \"IRANSans\";")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_wallet)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.btn_10 = QtWidgets.QPushButton(self.page_3)
        self.btn_10.setEnabled(True)
        self.btn_10.setGeometry(QtCore.QRect(220, 180, 62, 50))
        self.btn_10.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_10.setFont(font)
        self.btn_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_10.setMouseTracking(True)
        self.btn_10.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_10.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_10.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_10.setIcon(icon5)
        self.btn_10.setIconSize(QtCore.QSize(40, 40))
        self.btn_10.setFlat(False)
        self.btn_10.setObjectName("btn_10")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btn_11 = QtWidgets.QPushButton(self.page)
        self.btn_11.setEnabled(True)
        self.btn_11.setGeometry(QtCore.QRect(230, 170, 62, 50))
        self.btn_11.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_11.setFont(font)
        self.btn_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_11.setMouseTracking(True)
        self.btn_11.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_11.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_11.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/administrator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_11.setIcon(icon6)
        self.btn_11.setIconSize(QtCore.QSize(40, 40))
        self.btn_11.setFlat(False)
        self.btn_11.setObjectName("btn_11")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.btn_12 = QtWidgets.QPushButton(self.page_2)
        self.btn_12.setEnabled(True)
        self.btn_12.setGeometry(QtCore.QRect(210, 160, 63, 50))
        self.btn_12.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_12.setFont(font)
        self.btn_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_12.setMouseTracking(True)
        self.btn_12.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_12.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_12.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/office-material.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_12.setIcon(icon7)
        self.btn_12.setIconSize(QtCore.QSize(40, 40))
        self.btn_12.setFlat(False)
        self.btn_12.setObjectName("btn_12")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.btn_13 = QtWidgets.QPushButton(self.page_4)
        self.btn_13.setEnabled(True)
        self.btn_13.setGeometry(QtCore.QRect(230, 180, 62, 50))
        self.btn_13.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_13.setFont(font)
        self.btn_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_13.setMouseTracking(True)
        self.btn_13.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_13.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_13.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_13.setIcon(icon8)
        self.btn_13.setIconSize(QtCore.QSize(40, 40))
        self.btn_13.setFlat(False)
        self.btn_13.setObjectName("btn_13")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.btn_14 = QtWidgets.QPushButton(self.page_5)
        self.btn_14.setEnabled(True)
        self.btn_14.setGeometry(QtCore.QRect(220, 190, 62, 50))
        self.btn_14.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_14.setFont(font)
        self.btn_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_14.setMouseTracking(True)
        self.btn_14.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_14.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_14.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_14.setIcon(icon9)
        self.btn_14.setIconSize(QtCore.QSize(40, 40))
        self.btn_14.setFlat(False)
        self.btn_14.setObjectName("btn_14")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.btn_15 = QtWidgets.QPushButton(self.page_6)
        self.btn_15.setEnabled(True)
        self.btn_15.setGeometry(QtCore.QRect(210, 180, 63, 50))
        self.btn_15.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_15.setFont(font)
        self.btn_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_15.setMouseTracking(True)
        self.btn_15.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_15.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_15.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/network.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_15.setIcon(icon10)
        self.btn_15.setIconSize(QtCore.QSize(40, 40))
        self.btn_15.setFlat(False)
        self.btn_15.setObjectName("btn_15")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.btn_16 = QtWidgets.QPushButton(self.page_7)
        self.btn_16.setEnabled(True)
        self.btn_16.setGeometry(QtCore.QRect(200, 180, 62, 50))
        self.btn_16.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_16.setFont(font)
        self.btn_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_16.setMouseTracking(True)
        self.btn_16.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_16.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_16.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/laptop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_16.setIcon(icon11)
        self.btn_16.setIconSize(QtCore.QSize(40, 40))
        self.btn_16.setFlat(False)
        self.btn_16.setObjectName("btn_16")
        self.stackedWidget.addWidget(self.page_7)
        self.layoutWidget = QtWidgets.QWidget(self.tab_basic_info)
        self.layoutWidget.setGeometry(QtCore.QRect(481, 103, 203, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_user_full_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_user_full_name.setMinimumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_user_full_name.setFont(font)
        self.label_user_full_name.setStyleSheet("font: 8pt \"IRANSans\";\n"
"color:rgb(9, 9, 9);")
        self.label_user_full_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_full_name.setObjectName("label_user_full_name")
        self.verticalLayout.addWidget(self.label_user_full_name)
        self.label_company_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_company_name.setMinimumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_company_name.setFont(font)
        self.label_company_name.setStyleSheet("font: 9pt \"IRANSans\";\n"
"color:rgb(9,9,9);")
        self.label_company_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_company_name.setObjectName("label_company_name")
        self.verticalLayout.addWidget(self.label_company_name)
        self.label_company_branch = QtWidgets.QLabel(self.layoutWidget)
        self.label_company_branch.setMinimumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_company_branch.setFont(font)
        self.label_company_branch.setStyleSheet("font: 8pt \"IRANSans\";\n"
"color:rgb(9,9,9);")
        self.label_company_branch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_company_branch.setObjectName("label_company_branch")
        self.verticalLayout.addWidget(self.label_company_branch)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_basic_info)
        self.layoutWidget_2.setGeometry(QtCore.QRect(480, 230, 201, 191))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_setting = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_setting.setEnabled(True)
        self.btn_setting.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_setting.setFont(font)
        self.btn_setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_setting.setMouseTracking(True)
        self.btn_setting.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_setting.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_setting.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_setting.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon12)
        self.btn_setting.setIconSize(QtCore.QSize(40, 40))
        self.btn_setting.setFlat(False)
        self.btn_setting.setObjectName("btn_setting")
        self.gridLayout.addWidget(self.btn_setting, 0, 2, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_6.setEnabled(True)
        self.btn_6.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_6.setFont(font)
        self.btn_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_6.setMouseTracking(True)
        self.btn_6.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_6.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_6.setText("")
        self.btn_6.setIcon(icon8)
        self.btn_6.setIconSize(QtCore.QSize(40, 40))
        self.btn_6.setFlat(False)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 0, 1, 1)
        self.btn_wallet = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_wallet.setEnabled(True)
        self.btn_wallet.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_wallet.setFont(font)
        self.btn_wallet.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_wallet.setMouseTracking(True)
        self.btn_wallet.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_wallet.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_wallet.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_wallet.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/wallet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wallet.setIcon(icon13)
        self.btn_wallet.setIconSize(QtCore.QSize(40, 40))
        self.btn_wallet.setFlat(False)
        self.btn_wallet.setObjectName("btn_wallet")
        self.gridLayout.addWidget(self.btn_wallet, 0, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_3.setEnabled(True)
        self.btn_3.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_3.setFont(font)
        self.btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_3.setMouseTracking(True)
        self.btn_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_3.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_3.setText("")
        self.btn_3.setIcon(icon5)
        self.btn_3.setIconSize(QtCore.QSize(40, 40))
        self.btn_3.setFlat(False)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 0, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_5.setEnabled(True)
        self.btn_5.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_5.setFont(font)
        self.btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_5.setMouseTracking(True)
        self.btn_5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_5.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_5.setText("")
        self.btn_5.setIcon(icon7)
        self.btn_5.setIconSize(QtCore.QSize(40, 40))
        self.btn_5.setFlat(False)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_4.setEnabled(True)
        self.btn_4.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_4.setFont(font)
        self.btn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_4.setMouseTracking(True)
        self.btn_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_4.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_4.setText("")
        self.btn_4.setIcon(icon6)
        self.btn_4.setIconSize(QtCore.QSize(40, 40))
        self.btn_4.setFlat(False)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 2, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_7.setEnabled(True)
        self.btn_7.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_7.setFont(font)
        self.btn_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_7.setMouseTracking(True)
        self.btn_7.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_7.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_7.setText("")
        self.btn_7.setIcon(icon9)
        self.btn_7.setIconSize(QtCore.QSize(40, 40))
        self.btn_7.setFlat(False)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 2, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_9.setEnabled(True)
        self.btn_9.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_9.setFont(font)
        self.btn_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_9.setMouseTracking(True)
        self.btn_9.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_9.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_9.setText("")
        self.btn_9.setIcon(icon11)
        self.btn_9.setIconSize(QtCore.QSize(40, 40))
        self.btn_9.setFlat(False)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_8.setEnabled(True)
        self.btn_8.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_8.setFont(font)
        self.btn_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_8.setMouseTracking(True)
        self.btn_8.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_8.setStyleSheet("border-radius: 5px;\n"
"background-color:white;\n"
"color:white;")
        self.btn_8.setText("")
        self.btn_8.setIcon(icon10)
        self.btn_8.setIconSize(QtCore.QSize(40, 40))
        self.btn_8.setFlat(False)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 1, 1, 1)
        self.stackedWidget.raise_()
        self.line.raise_()
        self.lable_profile_image.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_2.raise_()
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_basic_info, icon14, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 20))
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statusBar.setStyleSheet("background-color:rgb(255, 234, 251);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setCheckable(False)
        self.actionProfile.setIcon(icon14)
        self.actionProfile.setObjectName("actionProfile")
        self.actionStore = QtWidgets.QAction(MainWindow)
        self.actionStore.setCheckable(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/img/Store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStore.setIcon(icon15)
        self.actionStore.setObjectName("actionStore")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.stackedWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Scroll Area "))
        self.label_17.setText(_translate("MainWindow", "Message3 Title (Header)"))
        self.label_18.setText(_translate("MainWindow", "Message1 Title (Header)"))
        self.label_19.setText(_translate("MainWindow", "Message2 Title (Header)"))
        self.label_6.setText(_translate("MainWindow", "محتوای پیام دریافت شده اینجا نمایش داده میشود"))
        self.label_9.setText(_translate("MainWindow", "Scroll Area "))
        self.label_2.setText(_translate("MainWindow", "Scroll Area "))
        self.label.setText(_translate("MainWindow", "Message1 Title (Header)"))
        self.label_15.setText(_translate("MainWindow", "Message2 Title (Header)"))
        self.label_16.setText(_translate("MainWindow", "Message3 Title (Header)"))
        self.label_7.setText(_translate("MainWindow", "محتوای پیام ارسال شده اینجا نمایش داده میشود"))
        self.label_8.setText(_translate("MainWindow", "Scroll Area "))
        self.lable_profile_image.setText(_translate("MainWindow", "img"))
        self.inq_ans_groupBox.setTitle(_translate("MainWindow", ":  نحوه پاسخ به استعلام "))
        self.radioButton.setText(_translate("MainWindow", "دستی"))
        self.radioButton_2.setText(_translate("MainWindow", "خودکار"))
        self.groupBox_select_software.setTitle(_translate("MainWindow", ": نرم افزار صندوق"))
        self.label_4.setText(_translate("MainWindow", "انتخاب نرم افزار :"))
        self.btn_cancel_login.setText(_translate("MainWindow", "انصراف"))
        self.groupBox_temp_password.setTitle(_translate("MainWindow", "ورود با یک بار رمز "))
        self.lineEdit_temp_password.setPlaceholderText(_translate("MainWindow", "رمز پیامک شده را اینجا وارد کنید ..."))
        self.btn_request_temp_pass.setText(_translate("MainWindow", "درخواست رمز یکبار مصرف"))
        self.label_10.setText(_translate("MainWindow", "شماره تلفن همراه :"))
        self.btn_enter_acnt.setText(_translate("MainWindow", "ورود به حساب کاربری"))
        self.btn_sign_up.setText(_translate("MainWindow", "ثبت نام"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.btn_10.setToolTip(_translate("MainWindow", "تنظیمات"))
        self.label_user_full_name.setText(_translate("MainWindow", "یوسف رستمیان"))
        self.label_company_name.setText(_translate("MainWindow", "فناوری اطلاعات نگارستان زرین"))
        self.label_company_branch.setText(_translate("MainWindow", "شعبه تهران"))
        self.btn_3.setToolTip(_translate("MainWindow", "تنظیمات"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionProfile.setToolTip(_translate("MainWindow", "<html><head/><body><p>پروفایل</p></body></html>"))
        self.actionStore.setText(_translate("MainWindow", "Store"))
        self.actionStore.setToolTip(_translate("MainWindow", "<html><head/><body><p>فروشگاه</p></body></html>"))


import Resource_rc
