# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/signup_confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signup_confirmation(object):
    def setupUi(self, Signup_confirmation):
        Signup_confirmation.setObjectName("Signup_confirmation")
        Signup_confirmation.resize(990, 595)
        Signup_confirmation.setMinimumSize(QtCore.QSize(990, 595))
        Signup_confirmation.setMaximumSize(QtCore.QSize(990, 595))
        self.btn_edit = QtWidgets.QPushButton(Signup_confirmation)
        self.btn_edit.setEnabled(True)
        self.btn_edit.setGeometry(QtCore.QRect(370, 530, 81, 41))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_edit.setFont(font)
        self.btn_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_edit.setMouseTracking(True)
        self.btn_edit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_edit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_edit.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(178, 55, 77);")
        self.btn_edit.setFlat(False)
        self.btn_edit.setObjectName("btn_edit")
        self.btn_confirm = QtWidgets.QPushButton(Signup_confirmation)
        self.btn_confirm.setEnabled(True)
        self.btn_confirm.setGeometry(QtCore.QRect(470, 530, 171, 41))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(11)
        font.setKerning(False)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_confirm.setMouseTracking(True)
        self.btn_confirm.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_confirm.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_confirm.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(58, 178, 151);")
        self.btn_confirm.setFlat(False)
        self.btn_confirm.setObjectName("btn_confirm")
        self.gbox_user_pass = QtWidgets.QGroupBox(Signup_confirmation)
        self.gbox_user_pass.setGeometry(QtCore.QRect(510, 40, 421, 461))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(9)
        self.gbox_user_pass.setFont(font)
        self.gbox_user_pass.setStyleSheet("border: 1px solid rgb(58, 178, 151);")
        self.gbox_user_pass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.gbox_user_pass.setObjectName("gbox_user_pass")
        self.label_4 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_4.setGeometry(QtCore.QRect(319, 44, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_nationalCode = QtWidgets.QLineEdit(self.gbox_user_pass)
        self.lineEdit_nationalCode.setGeometry(QtCore.QRect(49, 175, 261, 35))
        self.lineEdit_nationalCode.setMinimumSize(QtCore.QSize(261, 35))
        self.lineEdit_nationalCode.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_nationalCode.setMaxLength(10)
        self.lineEdit_nationalCode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nationalCode.setObjectName("lineEdit_nationalCode")
        self.label_7 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_7.setGeometry(QtCore.QRect(56, 343, 120, 90))
        self.label_7.setMinimumSize(QtCore.QSize(120, 90))
        self.label_7.setObjectName("label_7")
        self.lineEdit_address_3 = QtWidgets.QLineEdit(self.gbox_user_pass)
        self.lineEdit_address_3.setGeometry(QtCore.QRect(50, 266, 261, 35))
        self.lineEdit_address_3.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_address_3.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_address_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_address_3.setObjectName("lineEdit_address_3")
        self.label_2 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_2.setGeometry(QtCore.QRect(320, 136, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_5.setGeometry(QtCore.QRect(319, 183, 51, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_Email = QtWidgets.QLineEdit(self.gbox_user_pass)
        self.lineEdit_Email.setGeometry(QtCore.QRect(49, 221, 261, 35))
        self.lineEdit_Email.setMinimumSize(QtCore.QSize(261, 35))
        self.lineEdit_Email.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_Email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.label_6 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_6.setGeometry(QtCore.QRect(320, 227, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.gbox_user_pass)
        self.label.setGeometry(QtCore.QRect(320, 90, 31, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit_lastName = QtWidgets.QLineEdit(self.gbox_user_pass)
        self.lineEdit_lastName.setGeometry(QtCore.QRect(49, 129, 261, 35))
        self.lineEdit_lastName.setMinimumSize(QtCore.QSize(261, 35))
        self.lineEdit_lastName.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_lastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.label_3 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_3.setGeometry(QtCore.QRect(220, 323, 90, 120))
        self.label_3.setMinimumSize(QtCore.QSize(90, 120))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.gbox_user_pass)
        self.label_9.setGeometry(QtCore.QRect(320, 273, 61, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_firstName = QtWidgets.QLineEdit(self.gbox_user_pass)
        self.lineEdit_firstName.setGeometry(QtCore.QRect(49, 83, 261, 35))
        self.lineEdit_firstName.setMinimumSize(QtCore.QSize(261, 35))
        self.lineEdit_firstName.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_firstName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_firstName.setPlaceholderText("")
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.lineEdit_mobile = QtWidgets.QLineEdit(self.gbox_user_pass)
        self.lineEdit_mobile.setGeometry(QtCore.QRect(49, 37, 261, 35))
        self.lineEdit_mobile.setMinimumSize(QtCore.QSize(261, 35))
        self.lineEdit_mobile.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_mobile.setMaxLength(11)
        self.lineEdit_mobile.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.gbox_user_pass_2 = QtWidgets.QGroupBox(Signup_confirmation)
        self.gbox_user_pass_2.setGeometry(QtCore.QRect(50, 41, 421, 461))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(9)
        self.gbox_user_pass_2.setFont(font)
        self.gbox_user_pass_2.setStyleSheet("border: 1px solid rgb(58, 178, 151);")
        self.gbox_user_pass_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.gbox_user_pass_2.setObjectName("gbox_user_pass_2")
        self.lineEdit_address_2 = QtWidgets.QLineEdit(self.gbox_user_pass_2)
        self.lineEdit_address_2.setGeometry(QtCore.QRect(40, 83, 261, 35))
        self.lineEdit_address_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_address_2.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_address_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_address_2.setObjectName("lineEdit_address_2")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.gbox_user_pass_2)
        self.lineEdit_phone.setGeometry(QtCore.QRect(39, 176, 261, 35))
        self.lineEdit_phone.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_phone.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.label_27 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_27.setGeometry(QtCore.QRect(310, 229, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_company_name = QtWidgets.QLineEdit(self.gbox_user_pass_2)
        self.lineEdit_company_name.setGeometry(QtCore.QRect(39, 38, 261, 35))
        self.lineEdit_company_name.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("B Homa")
        font.setPointSize(10)
        self.lineEdit_company_name.setFont(font)
        self.lineEdit_company_name.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_company_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_company_name.setPlaceholderText("")
        self.lineEdit_company_name.setObjectName("lineEdit_company_name")
        self.lineEdit_address = QtWidgets.QLineEdit(self.gbox_user_pass_2)
        self.lineEdit_address.setGeometry(QtCore.QRect(39, 129, 261, 35))
        self.lineEdit_address.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_address.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.label_21 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_21.setGeometry(QtCore.QRect(310, 45, 91, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21.setLineWidth(0)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_8 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_8.setGeometry(QtCore.QRect(39, 274, 261, 161))
        self.label_8.setMinimumSize(QtCore.QSize(200, 150))
        self.label_8.setObjectName("label_8")
        self.label_28 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_28.setGeometry(QtCore.QRect(310, 334, 91, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.lineEdit_expert_code = QtWidgets.QLineEdit(self.gbox_user_pass_2)
        self.lineEdit_expert_code.setGeometry(QtCore.QRect(39, 222, 261, 35))
        self.lineEdit_expert_code.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("B Homa")
        font.setPointSize(10)
        self.lineEdit_expert_code.setFont(font)
        self.lineEdit_expert_code.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(236, 232, 228);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_expert_code.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_expert_code.setPlaceholderText("")
        self.lineEdit_expert_code.setObjectName("lineEdit_expert_code")
        self.label_26 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_26.setGeometry(QtCore.QRect(309, 137, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_24.setGeometry(QtCore.QRect(310, 182, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.gbox_user_pass_2)
        self.label_23.setGeometry(QtCore.QRect(310, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")

        self.retranslateUi(Signup_confirmation)
        QtCore.QMetaObject.connectSlotsByName(Signup_confirmation)

    def retranslateUi(self, Signup_confirmation):
        _translate = QtCore.QCoreApplication.translate
        Signup_confirmation.setWindowTitle(_translate("Signup_confirmation", "تایید نهایی"))
        self.btn_edit.setText(_translate("Signup_confirmation", "اصلاح"))
        self.btn_confirm.setText(_translate("Signup_confirmation", "تایید و ثبت نهایی"))
        self.gbox_user_pass.setTitle(_translate("Signup_confirmation", "اطلاعات مدیر/صاحب کسب و کار "))
        self.label_4.setText(_translate("Signup_confirmation", "تلفن همراه :"))
        self.label_7.setText(_translate("Signup_confirmation", "TextLabel"))
        self.label_2.setText(_translate("Signup_confirmation", "نام خانوادگی :"))
        self.label_5.setText(_translate("Signup_confirmation", "کد ملی :"))
        self.label_6.setText(_translate("Signup_confirmation", "آدرس ایمیل :"))
        self.label.setText(_translate("Signup_confirmation", "نام  :"))
        self.label_3.setText(_translate("Signup_confirmation", "TextLabel"))
        self.label_9.setText(_translate("Signup_confirmation", "تاریخ تولد :"))
        self.gbox_user_pass_2.setTitle(_translate("Signup_confirmation", "اطلاعات کسب و کار"))
        self.label_27.setText(_translate("Signup_confirmation", "کد کارشناس :"))
        self.label_21.setText(_translate("Signup_confirmation", "نام موسسه :"))
        self.label_8.setText(_translate("Signup_confirmation", "TextLabel"))
        self.label_28.setText(_translate("Signup_confirmation", "محل روی نقشه :"))
        self.label_26.setText(_translate("Signup_confirmation", "نشانی دقیق :"))
        self.label_24.setText(_translate("Signup_confirmation", "تلفن ثابت :"))
        self.label_23.setText(_translate("Signup_confirmation", "صنف :"))


