# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/signup_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup_wizard(object):
    def setupUi(self, signup_wizard):
        signup_wizard.setObjectName("signup_wizard")
        signup_wizard.resize(742, 527)
        signup_wizard.setMinimumSize(QtCore.QSize(742, 527))
        signup_wizard.setLayoutDirection(QtCore.Qt.RightToLeft)
        signup_wizard.setModal(True)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.label_5 = QtWidgets.QLabel(self.wizardPage1)
        self.label_5.setGeometry(QtCore.QRect(594, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_nationalCode = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_nationalCode.setGeometry(QtCore.QRect(324, 192, 261, 35))
        self.lineEdit_nationalCode.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_nationalCode.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_nationalCode.setMaxLength(10)
        self.lineEdit_nationalCode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nationalCode.setObjectName("lineEdit_nationalCode")
        self.label = QtWidgets.QLabel(self.wizardPage1)
        self.label.setGeometry(QtCore.QRect(595, 107, 31, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.toolButton_upload_card = QtWidgets.QToolButton(self.wizardPage1)
        self.toolButton_upload_card.setGeometry(QtCore.QRect(142, 248, 151, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_upload_card.setFont(font)
        self.toolButton_upload_card.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_upload_card.setStyleSheet("border:0px;\n"
"color:blue;")
        self.toolButton_upload_card.setObjectName("toolButton_upload_card")
        self.lineEdit_Email = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_Email.setGeometry(QtCore.QRect(324, 238, 261, 35))
        self.lineEdit_Email.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_Email.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_Email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.label_nationalCard = QtWidgets.QLabel(self.wizardPage1)
        self.label_nationalCard.setGeometry(QtCore.QRect(14, 217, 120, 90))
        self.label_nationalCard.setMinimumSize(QtCore.QSize(120, 90))
        self.label_nationalCard.setMouseTracking(True)
        self.label_nationalCard.setStyleSheet("background-color:white;")
        self.label_nationalCard.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nationalCard.setObjectName("label_nationalCard")
        self.lineEdit_firstName = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_firstName.setGeometry(QtCore.QRect(324, 100, 261, 35))
        self.lineEdit_firstName.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_firstName.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_firstName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.label_6 = QtWidgets.QLabel(self.wizardPage1)
        self.label_6.setGeometry(QtCore.QRect(595, 244, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.toolButton_upload_img = QtWidgets.QToolButton(self.wizardPage1)
        self.toolButton_upload_img.setGeometry(QtCore.QRect(142, 103, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_upload_img.setFont(font)
        self.toolButton_upload_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_upload_img.setStyleSheet("border:0px;\n"
"color:blue;")
        self.toolButton_upload_img.setObjectName("toolButton_upload_img")
        self.label_img = QtWidgets.QLabel(self.wizardPage1)
        self.label_img.setGeometry(QtCore.QRect(31, 50, 90, 120))
        self.label_img.setMinimumSize(QtCore.QSize(90, 120))
        self.label_img.setMouseTracking(True)
        self.label_img.setStyleSheet("background-color: white;")
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.lineEdit_birthYear = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_birthYear.setGeometry(QtCore.QRect(378, 284, 71, 35))
        self.lineEdit_birthYear.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_birthYear.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_birthYear.setMaxLength(4)
        self.lineEdit_birthYear.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_birthYear.setObjectName("lineEdit_birthYear")
        self.label_8 = QtWidgets.QLabel(self.wizardPage1)
        self.label_8.setGeometry(QtCore.QRect(527, 287, 16, 31))
        font = QtGui.QFont()
        font.setFamily("MSYekan")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.wizardPage1)
        self.label_7.setGeometry(QtCore.QRect(458, 287, 16, 31))
        font = QtGui.QFont()
        font.setFamily("MSYekan")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.toolButton_calendar = QtWidgets.QToolButton(self.wizardPage1)
        self.toolButton_calendar.setGeometry(QtCore.QRect(325, 284, 40, 35))
        self.toolButton_calendar.setMinimumSize(QtCore.QSize(40, 35))
        self.toolButton_calendar.setMaximumSize(QtCore.QSize(40, 35))
        self.toolButton_calendar.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;")
        self.toolButton_calendar.setObjectName("toolButton_calendar")
        self.label_9 = QtWidgets.QLabel(self.wizardPage1)
        self.label_9.setGeometry(QtCore.QRect(595, 290, 61, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_birthMonth = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_birthMonth.setGeometry(QtCore.QRect(478, 284, 41, 35))
        self.lineEdit_birthMonth.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_birthMonth.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_birthMonth.setMaxLength(2)
        self.lineEdit_birthMonth.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_birthMonth.setObjectName("lineEdit_birthMonth")
        self.lineEdit_birthDay = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_birthDay.setGeometry(QtCore.QRect(544, 284, 41, 35))
        self.lineEdit_birthDay.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_birthDay.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_birthDay.setMaxLength(2)
        self.lineEdit_birthDay.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_birthDay.setObjectName("lineEdit_birthDay")
        self.lbl_warning_msg = QtWidgets.QLabel(self.wizardPage1)
        self.lbl_warning_msg.setGeometry(QtCore.QRect(319, 343, 271, 41))
        self.lbl_warning_msg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_warning_msg.setStyleSheet("color:rgb(178, 55, 77);")
        self.lbl_warning_msg.setText("")
        self.lbl_warning_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_warning_msg.setObjectName("lbl_warning_msg")
        self.lineEdit_mobile = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_mobile.setGeometry(QtCore.QRect(324, 54, 261, 35))
        self.lineEdit_mobile.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_mobile.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_mobile.setMaxLength(11)
        self.lineEdit_mobile.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.label_4 = QtWidgets.QLabel(self.wizardPage1)
        self.label_4.setGeometry(QtCore.QRect(594, 61, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_lastName = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_lastName.setGeometry(QtCore.QRect(324, 146, 261, 35))
        self.lineEdit_lastName.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_lastName.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_lastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.label_2 = QtWidgets.QLabel(self.wizardPage1)
        self.label_2.setGeometry(QtCore.QRect(595, 153, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lbl_msg_check_mobile = QtWidgets.QLabel(self.wizardPage1)
        self.lbl_msg_check_mobile.setGeometry(QtCore.QRect(320, 10, 271, 41))
        self.lbl_msg_check_mobile.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_msg_check_mobile.setStyleSheet("color:rgb(178, 55, 77);")
        self.lbl_msg_check_mobile.setText("")
        self.lbl_msg_check_mobile.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_msg_check_mobile.setObjectName("lbl_msg_check_mobile")
        signup_wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.label_26 = QtWidgets.QLabel(self.wizardPage2)
        self.label_26.setGeometry(QtCore.QRect(594, 152, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.lineEdit_address = QtWidgets.QLineEdit(self.wizardPage2)
        self.lineEdit_address.setGeometry(QtCore.QRect(324, 144, 261, 35))
        self.lineEdit_address.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_address.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;")
        self.lineEdit_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.lineEdit_company_name = QtWidgets.QLineEdit(self.wizardPage2)
        self.lineEdit_company_name.setGeometry(QtCore.QRect(324, 53, 261, 35))
        self.lineEdit_company_name.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("B Homa")
        font.setPointSize(10)
        self.lineEdit_company_name.setFont(font)
        self.lineEdit_company_name.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;")
        self.lineEdit_company_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_company_name.setObjectName("lineEdit_company_name")
        self.toolButton_upload_permission = QtWidgets.QToolButton(self.wizardPage2)
        self.toolButton_upload_permission.setGeometry(QtCore.QRect(158, 105, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_upload_permission.setFont(font)
        self.toolButton_upload_permission.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_upload_permission.setStyleSheet("border:0px;\n"
"color:blue;")
        self.toolButton_upload_permission.setObjectName("toolButton_upload_permission")
        self.comboBox_guild = QtWidgets.QComboBox(self.wizardPage2)
        self.comboBox_guild.setGeometry(QtCore.QRect(324, 98, 261, 35))
        self.comboBox_guild.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBox_guild.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBox_guild.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;")
        self.comboBox_guild.setObjectName("comboBox_guild")
        self.label_21 = QtWidgets.QLabel(self.wizardPage2)
        self.label_21.setGeometry(QtCore.QRect(595, 60, 31, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21.setLineWidth(0)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.location_preview = QtWidgets.QLabel(self.wizardPage2)
        self.location_preview.setGeometry(QtCore.QRect(22, 193, 120, 120))
        self.location_preview.setMinimumSize(QtCore.QSize(120, 120))
        self.location_preview.setMouseTracking(True)
        self.location_preview.setStyleSheet("background-color : white;\n"
"")
        self.location_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.location_preview.setObjectName("location_preview")
        self.label_permission_img = QtWidgets.QLabel(self.wizardPage2)
        self.label_permission_img.setGeometry(QtCore.QRect(22, 70, 120, 90))
        self.label_permission_img.setMinimumSize(QtCore.QSize(120, 90))
        self.label_permission_img.setMouseTracking(True)
        self.label_permission_img.setStyleSheet("background-color : white;\n"
"")
        self.label_permission_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_permission_img.setObjectName("label_permission_img")
        self.toolButton_pin_location = QtWidgets.QToolButton(self.wizardPage2)
        self.toolButton_pin_location.setGeometry(QtCore.QRect(163, 243, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_pin_location.setFont(font)
        self.toolButton_pin_location.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_pin_location.setStyleSheet("border:0px;\n"
"color:blue;")
        self.toolButton_pin_location.setObjectName("toolButton_pin_location")
        self.label_23 = QtWidgets.QLabel(self.wizardPage2)
        self.label_23.setGeometry(QtCore.QRect(595, 105, 81, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.wizardPage2)
        self.lineEdit_phone.setGeometry(QtCore.QRect(324, 191, 261, 35))
        self.lineEdit_phone.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_phone.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;")
        self.lineEdit_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.label_24 = QtWidgets.QLabel(self.wizardPage2)
        self.label_24.setGeometry(QtCore.QRect(595, 197, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(self.wizardPage2)
        self.label_27.setGeometry(QtCore.QRect(595, 244, 71, 21))
        font = QtGui.QFont()
        font.setFamily("IRANSans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("font: 10pt \"IRANSans\";\n"
"border: 0px;")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_expert_code = QtWidgets.QLineEdit(self.wizardPage2)
        self.lineEdit_expert_code.setGeometry(QtCore.QRect(324, 237, 261, 35))
        self.lineEdit_expert_code.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("B Homa")
        font.setPointSize(10)
        self.lineEdit_expert_code.setFont(font)
        self.lineEdit_expert_code.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;")
        self.lineEdit_expert_code.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_expert_code.setObjectName("lineEdit_expert_code")
        self.lineEdit_password_conf = QtWidgets.QLineEdit(self.wizardPage2)
        self.lineEdit_password_conf.setGeometry(QtCore.QRect(324, 284, 125, 35))
        self.lineEdit_password_conf.setMinimumSize(QtCore.QSize(125, 35))
        self.lineEdit_password_conf.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_password_conf.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_password_conf.setObjectName("lineEdit_password_conf")
        self.lineEdit_password = QtWidgets.QLineEdit(self.wizardPage2)
        self.lineEdit_password.setGeometry(QtCore.QRect(459, 284, 125, 35))
        self.lineEdit_password.setMinimumSize(QtCore.QSize(125, 35))
        self.lineEdit_password.setStyleSheet("border:solid 5px;\n"
"background-color:rgb(204, 204, 204);\n"
"border-radius:5px;\n"
"font: 10pt \"B Homa\";")
        self.lineEdit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lbl_warning_msg_2 = QtWidgets.QLabel(self.wizardPage2)
        self.lbl_warning_msg_2.setGeometry(QtCore.QRect(319, 344, 271, 41))
        self.lbl_warning_msg_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_warning_msg_2.setStyleSheet("color:rgb(178, 55, 77);")
        self.lbl_warning_msg_2.setText("")
        self.lbl_warning_msg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_warning_msg_2.setObjectName("lbl_warning_msg_2")
        signup_wizard.addPage(self.wizardPage2)

        self.retranslateUi(signup_wizard)
        QtCore.QMetaObject.connectSlotsByName(signup_wizard)
        signup_wizard.setTabOrder(self.lineEdit_mobile, self.lineEdit_firstName)
        signup_wizard.setTabOrder(self.lineEdit_firstName, self.lineEdit_lastName)
        signup_wizard.setTabOrder(self.lineEdit_lastName, self.lineEdit_nationalCode)
        signup_wizard.setTabOrder(self.lineEdit_nationalCode, self.lineEdit_Email)
        signup_wizard.setTabOrder(self.lineEdit_Email, self.lineEdit_birthDay)
        signup_wizard.setTabOrder(self.lineEdit_birthDay, self.lineEdit_birthMonth)
        signup_wizard.setTabOrder(self.lineEdit_birthMonth, self.lineEdit_birthYear)
        signup_wizard.setTabOrder(self.lineEdit_birthYear, self.toolButton_upload_img)
        signup_wizard.setTabOrder(self.toolButton_upload_img, self.toolButton_upload_card)
        signup_wizard.setTabOrder(self.toolButton_upload_card, self.toolButton_calendar)
        signup_wizard.setTabOrder(self.toolButton_calendar, self.lineEdit_company_name)
        signup_wizard.setTabOrder(self.lineEdit_company_name, self.comboBox_guild)
        signup_wizard.setTabOrder(self.comboBox_guild, self.lineEdit_address)
        signup_wizard.setTabOrder(self.lineEdit_address, self.lineEdit_phone)
        signup_wizard.setTabOrder(self.lineEdit_phone, self.lineEdit_expert_code)
        signup_wizard.setTabOrder(self.lineEdit_expert_code, self.toolButton_upload_permission)
        signup_wizard.setTabOrder(self.toolButton_upload_permission, self.toolButton_pin_location)
        signup_wizard.setTabOrder(self.toolButton_pin_location, self.lineEdit_password)
        signup_wizard.setTabOrder(self.lineEdit_password, self.lineEdit_password_conf)

    def retranslateUi(self, signup_wizard):
        _translate = QtCore.QCoreApplication.translate
        signup_wizard.setWindowTitle(_translate("signup_wizard", "Wizard"))
        self.label_5.setText(_translate("signup_wizard", "کد ملی :"))
        self.label.setText(_translate("signup_wizard", "نام  :"))
        self.toolButton_upload_card.setText(_translate("signup_wizard", "... بارگذاری تصویر کارت ملی"))
        self.label_nationalCard.setText(_translate("signup_wizard", "TextLabel"))
        self.lineEdit_firstName.setPlaceholderText(_translate("signup_wizard", "نام مدیر یا مالک کسب و کار"))
        self.label_6.setText(_translate("signup_wizard", "آدرس ایمیل :"))
        self.toolButton_upload_img.setText(_translate("signup_wizard", "... بارگذاری عکس پرسنلی"))
        self.label_img.setText(_translate("signup_wizard", "TextLabel"))
        self.label_8.setText(_translate("signup_wizard", "/"))
        self.label_7.setText(_translate("signup_wizard", "/"))
        self.toolButton_calendar.setText(_translate("signup_wizard", "..."))
        self.label_9.setText(_translate("signup_wizard", "تاریخ تولد :"))
        self.label_4.setText(_translate("signup_wizard", "تلفن همراه :"))
        self.label_2.setText(_translate("signup_wizard", "نام خانوادگی :"))
        self.label_26.setText(_translate("signup_wizard", "نشانی دقیق :"))
        self.lineEdit_company_name.setPlaceholderText(_translate("signup_wizard", "نام  فروشگاه / موسسه / شرکت ..."))
        self.toolButton_upload_permission.setText(_translate("signup_wizard", "... بارگذاری تصویر مجوز"))
        self.label_21.setText(_translate("signup_wizard", "نام :"))
        self.location_preview.setText(_translate("signup_wizard", "TextLabel"))
        self.label_permission_img.setText(_translate("signup_wizard", "TextLabel"))
        self.toolButton_pin_location.setText(_translate("signup_wizard", "... موقعیت روی نقشه"))
        self.label_23.setText(_translate("signup_wizard", "صنف :"))
        self.label_24.setText(_translate("signup_wizard", "تلفن ثابت :"))
        self.label_27.setText(_translate("signup_wizard", "کد کارشناس :"))
        self.lineEdit_expert_code.setPlaceholderText(_translate("signup_wizard", "کد کارشناس نصب نرم افزار"))
        self.lineEdit_password_conf.setPlaceholderText(_translate("signup_wizard", "تکرار رمز عبور ..."))
        self.lineEdit_password.setPlaceholderText(_translate("signup_wizard", "رمز عبور ..."))


